# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98980e70a97e83456ed0e0c341df34ebc69ed61de198867c1ee05c134c280411cf8563cf9ce5a326728597e45939b6150eec8d1b32013b7699da36090949fb3b

test:
  secret_key_base: 4ecb4e76252932a9a68954b2e2adb353cbf8c2bcc0b63d71b8b1515a38113ee2e7032ca7028392a245ee860690a4886a08820676cbf3ac0115b173a05e288573

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
